### ISSUE TITLE
vue3.x This tool is not available

### ISSUE THREAD

**Issue by hdj158** [sockjs/sockjs-client#570] opened 2022-01-19 07:48 UTC
Uncaught ReferenceError: global is not defined
    at node_modules/sockjs-client/lib/utils/event.js (event.js:8)
    at __require (chunk-UIXH5OZO.js?v=54df7975:29)
    at node_modules/sockjs-client/lib/transport/websocket.js (websocket.js:3)
    at __require (chunk-UIXH5OZO.js?v=54df7975:29)
    at node_modules/sockjs-client/lib/transport-list.js (transport-list.js:5)
    at __require (chunk-UIXH5OZO.js?v=54df7975:29)
    at node_modules/sockjs-client/lib/entry.js (entry.js:3)
    at __require (chunk-UIXH5OZO.js?v=54df7975:29)
    at dep:sockjs-client:1

**Comment by brycekahle** [comment] 2022-02-27 19:30
Duplicate of #565

**Closed by brycekahle** 2022-02-27 19:30 UTC
