### ISSUE TITLE
Transport Timeout doesn't close that connection

### ISSUE THREAD

**Issue by WenderGalan** [sockjs/sockjs-client#582] opened 2022-03-03 17:50 UTC
Guys, I'm having the same problem in version v1.5.0, I updated to version v1.6.0 but the problem still occurs, after the browser is minimized for a few minutes, the infinite loop starts and even the application requests crash.

As reported in the issue https://github.com/sockjs/sockjs-client/issues/334 I am having this issue now again, does anyone know what can be done?

I'm thinking of removing the library for another one because we can't find a solution to the problem.

![image](https://user-images.githubusercontent.com/30455044/156622548-c4c373f8-00d8-4f43-93ed-161f4a599ff2.png)

**Comment by FZambia** [comment] 2022-03-03 17:55
@WenderGalan hello, could you provide a minimal code and steps to reproduce this? I am pretty sure that if you provide those then the fix will be found quickly.

**Comment by WenderGalan** [comment] 2022-03-03 17:55
@brycekahle any thoughts? Do you have enough information to understand what's going on here?

**Comment by WenderGalan** [comment] 2022-03-03 17:57
So, the code I think any one will do, I tested it both in chrome and in edge and the problem appeared, basically you start the websocket communication and leave the browser in the background and you can go mess with other things, you can't keep it open, minutes later this starts to happen.

**Comment by WenderGalan** [comment] 2022-03-03 18:00
Apparently after a while something happens in the browser in the background I don't know why, inside the spring boot application there is no error log or something like that.

**Comment by MatheusPimentel** [comment] 2022-03-03 18:01
mesmo problema aqui

**Comment by WenderGalan** [comment] 2022-03-03 18:04
@FZambia @brycekahle any thoughts? Do you have enough information to understand what's going on here?

The correction of the other issue is correct in my node_modules but it doesn't work.

![image](https://user-images.githubusercontent.com/30455044/156624640-b5fae25f-1bc6-4316-9a0b-f1c4ab79c978.png)

**Comment by WenderGalan** [comment] 2022-03-03 18:12
![image](https://user-images.githubusercontent.com/30455044/156626124-5356864c-dc25-459d-838f-1614d8c34a4c.png)

**Comment by FZambia** [comment] 2022-03-04 10:35
> So, the code I think any one will do, I tested it both in chrome and in edge and the problem appeared, basically you start the websocket communication and leave the browser in the background and you can go mess with other things, you can't keep it open, minutes later this starts to happen.

SockJS client works without issues for me in minimized tab. Chrome 98 on MacOS. And I am not using Spring/Stomp.

It's hard to guess the reason of issue in your case. May be caused by browser throttling strategies (maybe specific to some OS?), wrapping code around SockJS, or maybe some special condition happening on Spring server-side which causes reconnect with broken reconnect logic in Stomp. Or triggered by some proxy between? So again - if you provide a code snippet (ideally using pure SockJS client) with OS description, setup specifics and exact steps to reproduce this may help finding a root cause.

Also. I don't understand why you think the reason of this is transport timeout. There is nothing in your report points at this as a real root cause. It may be though.

P.S. I am not a maintainer of this library.

**Comment by brycekahle** [comment] 2022-03-07 21:13
@WenderGalan I'm afraid I can't help you debug setups that involve other software. If the problem is not with sockjs-client, please close the issue.

**Closed** 2022-03-08 13:13 UTC
