### ISSUE TITLE
Connection aborted due to invalid data in the socket in Firefox

### ISSUE THREAD

**Issue by miketaylr** [sockjs/sockjs-client#474] opened 2019-04-11 18:18 UTC
This bug was filed @ https://bugzilla.mozilla.org/show_bug.cgi?id=1536843 and also https://github.com/facebook/create-react-app/issues/6720, but it seems like the bug is here in sockjs-client (I think?).

There's STR in https://bugzilla.mozilla.org/show_bug.cgi?id=1536843#c0.

> It shows that the websocket handshake is successful, few frames are received, but then the connection is aborted due to invalid data in the socket.

> In the end, I was able to reproduce it and mozregression pointed to a bug 1417463. That bug changed default accept header and further testing showed that it's server side issue. For some reason, server goes mad when "text/html" is missing in the accept header and after few frames it sends some unexpected HTTP response over the websocket connection.

> I.e. this bug happens in Firefox 65 too when text/html is removed from network.http.accept.default pref in about:config.

**Comment by brycekahle** [comment] 2019-04-13 17:26
@miketaylr Those comments seem to indicate a server issue? If that is correct, it is not a bug in sockjs-client.

**Comment by daliusd** [comment] 2019-04-13 18:58
Yes, I think this might be webpack-dev-server issue, but I'm not sure.

**Comment by evilebottnawi** [comment] 2019-04-13 19:13
@brycekahle Nope, problem here

**Comment by brycekahle** [comment] 2019-04-13 20:01
@evilebottnawi Please explain. The comments above clearly reference a "server side issue", which would not be the JS client.

**Comment by dmile** [comment] 2019-04-14 04:25
Connection aborted because webpack-dev-server trying to proxy sockjs request

1. When proxy enabled webpack-dev-server uses http-proxy-middleware
2. http-proxy-middleware checks every request with [shouldProxy](https://github.com/chimurai/http-proxy-middleware/blob/b13302c87a04bf7adc4c2547affaaeeb7ecb0c42/src/http-proxy-middleware.ts#L92) and result depends on proxy context
3. Default proxy context defined in react-dev-utils and [rely on accept header](https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/WebpackDevServerUtils.js#L404)
4. The header is different for browsers

Firefox 65.0.2
<img width="1437" alt="Firefox 65.0.2" src="https://user-images.githubusercontent.com/11796606/56088155-29216e80-5e8c-11e9-8025-262342081a40.png">
Firefox 66.0.3
<img width="1437" alt="Firefox 66.0.3" src="https://user-images.githubusercontent.com/11796606/56088156-30487c80-5e8c-11e9-8dd6-9efb5a7c0a9c.png">

Hope it helps.

**Comment by dmile** [comment] 2019-04-14 05:38
Interesting that Safari doesn't send `accept` header at all.
In that case `context` / `sholdProxy` becomes `undefined` and works fine in `if` condition with enabling HPM stuff :slightly_smiling_face:

**Comment by brycekahle** [comment] 2019-04-14 17:47
@dmile Thanks for the info. That seems to indicate the problem lies in `react-dev-utils` then. Would you agree?

**Comment by dmile** [comment] 2019-04-15 05:41
It's an integration issue. But I agree, `react-dev-utils` is a place where it occurs.

**Comment by brycekahle** [comment] 2019-04-15 18:44
I'm going to close this issue since the problem lies elsewhere.

**Closed by brycekahle** 2019-04-15 18:44 UTC
