### ISSUE TITLE
Remove json3 dependency

### ISSUE THREAD

**Issue by DaSchTour** [sockjs/sockjs-client#498] opened 2020-02-26 21:31 UTC
As stated in the [libraries homepage json3](https://bestiejs.github.io/json3/) is deprecated and migration to native JSON functions should be done.
This would help decreasing library size and possibly make it faster.

**Comment by brycekahle** [comment] 2020-02-26 21:40
Duplicate of #476

**Closed by brycekahle** 2020-02-26 21:40 UTC
