### ISSUE TITLE
Ready state value will be still 0 even after the successful websocket connection with the client. 

### ISSUE THREAD

**Issue by chirag93** [sockjs/sockjs-client#266] opened 2015-11-02 07:04 UTC
Even though the websocket connection is successful with the server the ready state value will still  be 0 and throws the exception "InvalidStateError: The connection has not been established yet" . This is being observed when the server is busy.  
It looks like the state will be still in the 'connecting' even after the connection. This is being observed only when the server is busy .
Shouldn't the state change cycle be like CONNECTING ->  CONNECTED.

**Comment by brycekahle** [comment] 2015-11-02 18:55
The connecting is not marked as `OPEN` until it receives a specific message from the server.

**Comment by chirag93** [comment] 2015-11-03 05:50
But the connection between server and the client has been successfully established, after onopen is called the readystate value will still be 0.

**Comment by brycekahle** [comment] 2015-11-03 17:55
Can you link to the offending code? I'm not following your description.

**Comment by chirag93** [comment] 2015-11-05 05:53
I'm not observing this issue consistently, Its happening only on few cases will debug more. 
Just as a note primus has the same issue. https://github.com/primus/primus/issues/320

**Comment by lpinca** [comment] 2015-11-05 07:41
@chirag93 the problem in primus is caused by a race condition but it's a primus issue not a sockjs one.

**Closed** 2015-11-17 09:21 UTC
