### ISSUE TITLE
sockjs closes and reconnects automatically every second in IE9

### ISSUE THREAD

**Issue by beamofsoul** [sockjs/sockjs-client#347] opened 2016-11-23 07:32 UTC
I am trying to use sockjs as a client for my websocket demo which based on springboot. 
Some say that sockjs is a kind of solution to make websocket looks fine in low version IE (eg. IE9). 
But in my demo, it closes and reconnects automatically, and makes IE pops up a new tab (with new random URL like my project path + '/727/xno5iiuy/htmlfile?c=_jp.a4sbalw') every second.
I do not know the reason just because it is nothing wrong when in Chrome.

```
        sock = new SockJS(url, undefined, {transports: transports});

        sock .onopen = function() {
		console.log('open');
	};
	sock .onmessage = function(e) {
		console.log('message', e.data);
	};
	sock .onclose = function() {
		console.log('close');
	};
	sock .onheartbeat = function() {
	    console.log('heartbeat');
	};
```

Could someone help me, plz? 
Thanks in advance.

**Comment by stewartie4** [comment] 2016-11-25 00:21
Having the exact same issue,only it is popping up a new window for me every second meaning I cannot close then quick enough nor get a look into the console

**Comment by stewartie4** [comment] 2016-11-25 00:33
After a little bit of poking around this seems to be a regression all the way back from 0.3.4 . 
Unfortunately reverting to that version will not help as stomp simply fails to connect at all.

**Comment by stewartie4** [comment] 2016-12-23 03:28
@beamofsoul did you ever figure out how to fix the issue?

**Comment by beamofsoul** [comment] 2016-12-26 16:17
@stewartie4 unfortunately no, i have tried a few different ways to fix it, but did not work. so just waiting and keep trying...

**Comment by brycekahle** [comment] 2017-01-04 15:48
This appears to be a duplicate of #308, but I can't be sure without more information. Can you post debug logs or the Network tab in Chrome?

**Comment by stewartie4** [comment] 2017-01-04 22:49
Thanks for the reply, I don't know about @beamofsoul

**Comment by brycekahle** [comment] 2017-01-23 02:44
Closing as duplicate of #308

**Closed by brycekahle** 2017-01-23 02:44 UTC
