### ISSUE TITLE
chrome console show error

### ISSUE THREAD

**Issue by shreychaturvedi123** [sockjs/sockjs-client#387] opened 2017-06-29 09:11 UTC
Uncaught Error: Incompatibile SockJS! Main site uses: "1.1.4", the iframe: "1.0.1".
Issue on google chrome and connection is lost by using sockjs client with stomp

**Comment by brycekahle** [comment] 2017-06-29 15:36
Duplicate of https://github.com/sockjs/sockjs-node/issues/230

**Closed by brycekahle** 2017-06-29 15:36 UTC
