### ISSUE TITLE
SyntaxError: The URL's scheme must be either 'http:' or 'https:'. 'wss:' is not allowed.

### ISSUE THREAD

**Issue by akl7777777** [sockjs/sockjs-client#621] opened 2023-02-27 05:17 UTC
SyntaxError: The URL's scheme must be either 'http:' or 'https:'. 'wss:' is not allowed.

I am requesting a certain wss, but this error is reported, is the URL starting with wss not supported?

**Comment by auvipy** [comment] 2023-02-27 07:05
can you provide a failing test to verify?

**Comment by FZambia** [comment] 2023-04-16 13:03
Duplicate of https://github.com/sockjs/sockjs-client/issues/452

**Closed** 2023-04-17 04:35 UTC
