### ISSUE TITLE
WebsocketDriver is not a constructor

### ISSUE THREAD

**Issue by vvpvvp** [sockjs/sockjs-client#354] opened 2017-01-16 07:09 UTC
I used it in webpack, and I don't know why?

**Comment by brycekahle** [comment] 2017-01-21 17:41
Sounds like a duplicate of #321

**Closed by brycekahle** 2017-01-21 17:41 UTC

**Comment by vvpvvp** [comment] 2017-02-25 09:10
Thanks.
And finally, I found the problem, when I reloaded chrome, everything is good.
So, sometimes, We can't always trust it.
