### ISSUE TITLE
sockjs closes connection after 60 seconds

### ISSUE THREAD

**Issue by norbertpy** [sockjs/sockjs-client#285] opened 2016-01-16 20:05 UTC
When connected to a server, I have noticed that the connection is closed automatically after **60 seconds**. It's between **59900 - 60100 ms** normally. I don't seem to find anything in the documentation regarding this.

- Is this an expected behavior? 
- If not, how to prevent or debug it? 
- How can I have a long running connection? 
- Is this only valid for inactivity?

The heartbeat from server is set to 25 seconds by default but the `onheatbeat` function is only called once and that's during the connection initiation. Please note that I have disabled `websocket` protocol on the server and the client only uses the following protocols.

```javascript
// client.js
var sock = new SockJS('https://server/rt', null, {
    transports: ['xdr-streaming', 'xhr-streaming', 'iframe-eventsource', 
                 'iframe-htmlfile', 'xdr-polling', 'xhr-polling', 
                 'iframe-xhr-polling', 'jsonp-polling'
    ]
});

sock.onopen = function() {
    console.log('open');
};

sock.onmessage = function(e) {
    console.log('onmessage');
};

sock.onheartbeat = function() {
    console.log('heartbeat'); // ONLY CALLED ONCE
};

sock.onclose = function() {
    console.log('close');
}
```

**Comment by karankap** [comment] 2016-02-23 12:17
I am facing similar issue, were you able to resolve the above problem? If yes, please share the resolution steps

**Comment by norbertpy** [comment] 2016-02-25 15:40
@karankap , nope. As you can see this project is pretty inactive. I decided to ditch websocket all together.

**Comment by tmds** [comment] 2016-02-25 15:54
Probably this info is useful to help debug the problem:
- which version of server&client are you using
- on which transports do you see the time out
- are your browser and server on the same network or might there be intermediate proxies which close the connection
- what browser(s) are you using
- anything of interest you have observed

**Comment by norbertpy** [comment] 2016-02-25 17:20
@tmds,
- sockjs-client `1.0.3` and sockjs-tornado `1.0.0`
- Mostly `xhr-streaming`
- proxies are there
- all browsers have the same issue

**Comment by tmds** [comment] 2016-02-25 17:30
What do you mean by 'proxies are there'?
Can you check whether the connection is closed by the browser or by the server side?
What browsers have you tested with?

**Comment by norbertpy** [comment] 2016-02-25 17:41
I'll create a small example tonight without any proxy and share you the link.

**Comment by norbertpy** [comment] 2016-02-26 19:31
@tmds check this out. Don't forget to open your console.

live: https://sockjs-connection-timeout-norbertpy.c9users.io/index.html
code: https://ide.c9.io/norbertpy/sockjs-connection-timeout

**Comment by tmds** [comment] 2016-02-26 21:54
I checked out your sample.
It looks like when the server closes the POST request to 'xhr_streaming' it doesn't end the chunked encoding in a proper way.
This is what the RFC says (http://tools.ietf.org/html/rfc7230#section-4.1)
"The chunked transfer coding is complete
   when a chunk with a chunk-size of zero is received, possibly followed
   by a trailer, and finally terminated by an empty line."
Wireshark shows these bytes are not there.

As a consequence the connection is closed by the client library as it assumes something went wrong.

In chrome you can see the ERR_INCOMPLETE_CHUNKED_ENCODING show up in the console.

**Comment by norbertpy** [comment] 2016-02-26 22:09
Well, I've seen that but I'm confused as to whether it's a bug or feature? I assume it's a bug in client side. Is that correct?

**Comment by tmds** [comment] 2016-02-26 22:14
So, now we can wonder why the server closes the connection in an inapproriate way...
Probably the server side closes it due to inactivity. But the sockjs server implementation should avoid that by sending heartbeats. So perhaps something is not working properly on that end.

**Comment by tmds** [comment] 2016-02-26 22:18
@mrjoes This looks like a bug in sockjs-tornado.

**Comment by norbertpy** [comment] 2016-02-26 22:21
Just in case you wanted to test again on my sample, hand me your email and I'll give edit permission on cloud9 workspace. Mainly because if I shut down my computer the cloud9 container will stop but if you have edit access you can run it again.

Thanks again.

**Comment by mrjoes** [comment] 2016-02-29 16:48
sockjs-tornado is not compatible with the latest version of the sockjs protocol. Latest supported version is 0.3.4 and heartbeats were not part of the spec back then.

**Comment by norbertpy** [comment] 2016-02-29 17:12
@mrjoes Would you please add that to the documentation. Since sockjs is a collection of projects it's good if you explicitly add. 

I think we had a relevant problem with 0.3.4 as well. I'll check.

**Comment by mrjoes** [comment] 2016-02-29 17:43
I checked - it does not send empty frame to close xhr-streaming transport, but I was not able to find it in the 0.3.4 protocol spec either - there's only mention to close connection after 128 KB worth of sent data.

On other hand, I have no idea why server closes connection after 60 seconds. Do you have any sort of load balancer in front of the sockjs-tornado? If yes, that might be the cause.

**Comment by norbertpy** [comment] 2016-02-29 19:18
@mrjoes the example I linked above is on cloud9. No proxy as far as I know and the connection closes after 30 seconds.

**Comment by mrjoes** [comment] 2016-03-02 16:04
It is quite possible that cloud9 is closing long-running connections.

Can you reproduce is with a local server?

**Closed** 2016-04-30 20:33 UTC
