### ISSUE TITLE
Npm install doesn't include dist

### ISSUE THREAD

**Issue by robertdempsey** [sockjs/sockjs-client#335] opened 2016-09-28 10:46 UTC
Hi,

Great library, using it at work for all of our websocket stuff. I'm in a bit of a bind though, I would like to get rid of the need for bower (even if I have to use it, it doesn't seem to be playing nicely with webpack) but when I install this through npm, the dist directory doesn't come along (I see it's included in .npmignore).

Is this required for the library to work? If I download it manually and put it in my node_modules, everything is hunky dory. Should the dist directory be removed from .npmignore?

Cheers
Rob

**Comment by kisdaniel** [comment] 2016-10-15 10:05
Will it be solved?

**Comment by afinnell** [comment] 2016-10-19 18:16
I am floored by the exclusion of the dist directory as well.. I just tried to use the npm version of this library only to discover that the AMD compatible files don't get included.. Such a shame. We can fork this repo then install it via the github+npm interface at least.

**Comment by afinnell** [comment] 2016-10-19 18:22
For anyone needing an immediate fix change your package.json to use this instead: 

"sockjs-client": "github:parlew/sockjs-client"

It now includes the dist directory.

**Comment by brycekahle** [comment] 2016-10-19 18:34
Duplicate of #265

**Closed by brycekahle** 2016-10-19 18:34 UTC

**Comment by dbashford** [comment] 2016-11-14 21:25
Excluding `dist` is a remarkably poor decision.

**Comment by dbashford** [comment] 2016-11-14 21:33
@afinnell Any chance you could publish that to NPM as '@parlew/sockjs-client'?

For example: 

https://github.com/Mind-Trace/stomp-websocket/blob/master/package.json#L2.
https://www.npmjs.com/package/@mind-trace/stompjs

We aren't able to use GH dependencies via NPM from our build environment.

**Comment by dbashford** [comment] 2016-11-15 15:05
@afinnell nevermind, didn't realize that is how private packages work.

I published sockjs-client-web to NPM. In a bit of a crunch. =)
