### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by danielbronder** [sockjs/sockjs-client#360] opened 2017-03-06 10:09 UTC
I have an issue with creating a websocket connection to our server. When I create a websocket connection to the server I get an error with : 

`No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8090' is therefore not allowed access. The response had HTTP status code 403.`

This error only appears when I do not have a tab open with the website. When I do have a tab open with our website it works fine. 

I was searching for a solution to set a header in the conenction. I have seen some solutions, but I can't get it to work. I have also read that it might not be possible set a header on the sockJs client side. 

This is my code:

` $scope.startWebsocket = function () {
            var socket = new SockJS('https://www.example.com/socket?token=125334fe-85e0-4967-86dc-60e8d637d131');
            var stompClient = Stomp.over(socket);
            stompClient.connect({}, function () {
                stompClient.subscribe('/trades', function (data) {
                    console.log(data)
                });
            }, function () {
                console.log("Connection not possible")
            });
        };`

I hope someone can explain this issue and help me.

**Comment by brycekahle** [comment] 2017-03-14 14:46
The problem is not a missing header on the request, but the server response. This is called CORS. SockJS servers will add this by default. You don't mention what you are using for a server, but I would look there. The error message you posted also mentioned a status code of `403`, which may be contributing to the problem.

Closing as this is not a client issue.

**Closed by brycekahle** 2017-03-14 14:46 UTC
