### ISSUE TITLE
SockJS Fails in Safari 8

### ISSUE THREAD

**Issue by blittle** [sockjs/sockjs-client#312] opened 2016-05-20 18:01 UTC
SockJS fails due to a type error in Safari 7 and 8.

Safari thinks that this is an invalid constructor of a native socket: https://github.com/sockjs/sockjs-client/blob/master/lib/transport/websocket.js#L32

![image](https://cloud.githubusercontent.com/assets/1566869/15437083/5fbb2884-1e82-11e6-8fa8-8f9401e9d576.png)

The WebSocket constructor takes two arguments, not 3, and Safari doesn't like the third:

https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

**Comment by brycekahle** [comment] 2016-05-20 18:25
Duplicate of #309

**Closed by brycekahle** 2016-05-20 18:25 UTC

**Comment by brycekahle** [comment] 2016-05-20 18:27
1.1.1 published with a fix.

**Comment by blittle** [comment] 2016-05-20 18:45
Thanks!
